Controllers/Ejercicio3/VisitasController.cs
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EJERCICIOS.Models;
using System.IO;
using System.Threading.Tasks;

namespace EJERCICIOS.Controllers
{
    public class VisitasController : Controller
    {
        public IActionResult Index()
        {

            List<Visitas> visitas = new List<Visitas>();

            visitas = leerArchivo();

            return View(visitas);
        }

        public IActionResult Registrar()
        {
            List<Visitas> comentarios = new List<Visitas>();


            comentarios = leerArchivo();

            var nuevoID = comentarios.Count;

            ViewData["nuevoID"] = nuevoID + 1;
            return View();
        }

        public ActionResult Editar(int? id)
        {

            List<Visitas> comentarios = new List<Visitas>();


            comentarios = leerArchivo();

            Visitas comEncontrado = comentarios.Find(x => x.ID == id);

            ViewData["Comentario"] = comEncontrado;

            return View();

        }

        public ActionResult Eliminar(int? id)
        {
            var x = Convert.ToInt32(id);
            string dataPath = @"D:\Trabajo\Capacitacion\C#\archivos\Libro de Visitas.txt";
            string[] readText = System.IO.File.ReadAllLines(dataPath);
            readText[x] = "";
            System.IO.File.WriteAllLines(dataPath, readText);
            return View();
        }

        public List<Visitas> leerArchivo()
        {
            string dataPath = @"D:\Trabajo\Capacitacion\C#\archivos\Libro de Visitas.txt";

            List<Visitas> visitas = new List<Visitas>();

            if (!System.IO.File.Exists(dataPath))
            {
                // Create a file to write to.
                string createText = "Nombre" + "," + "Pais" + "," + "Comentario";
                System.IO.File.WriteAllText(dataPath, createText);
            }


            string[] readText = System.IO.File.ReadAllLines(dataPath);


            for (var i = 1; i < readText.Length;)
            {
                if (readText[i] == "")
                { i++; }
                else
                {
                    var x = readText[i].Split(",");
                    visitas.Add(new Visitas
                    {
                        ID = i,
                        Nombre = x[0],
                        Pais = x[1],
                        Comentario = x[2]

                    });
                    i++;
                }

            }

            return visitas;
        }

    }
}

Controllers/Ejercicio4/AgendaController.cs
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc;
using EJERCICIOS.Models;

namespace EJERCICIOS.Controllers
{
    public class AgendaController : Controller
    {
        public IActionResult Agenda()
        {
            var agenda = leerAgenda();

            return View(agenda);
        }

        private List<Agenda> leerAgenda()
        {
            List<Agenda> agenda = new List<Agenda>();
            var dataPath = @"D:\Trabajo\Capacitacion\C#\archivos\Agenda.txt";

            if (!System.IO.File.Exists(dataPath))
            {
                // Create a file to write to.
                string createText = "Fecha" + "," + "Horario" + "," + "Actividad" + "," + "Nota" + Environment.NewLine;
                System.IO.File.WriteAllText(dataPath, createText);
            }

            string[] readText = System.IO.File.ReadAllLines(dataPath);

            for (var i = 1; i < readText.Length; i++)
            {
                var x = readText[i].Split(",");
                agenda.Add(new Agenda
                {
                    ID = i,
                    Fecha = x[0],
                    Horario = x[1],
                    Actividad = x[2],
                    Nota = x[3],

                });
            }

            return agenda;
        }

        public IActionResult RegistroNuevo()
        {
            //ViewData["Fecha"] = DateTime.Now.ToString("yyyy-MM-ddThh:mm");
            ViewData["Fecha"] = DateTime.Now.ToString("yyyy-MM-dd");
            ViewData["Hora"] = DateTime.Now.ToString("hh:mm");

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EJERCICIOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <environment include="Development">
        <link rel="stylesheet" href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" type="text/css" />
    </environment>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EJERCICIOS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendario"
                                asp-action="Index">Calendario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TPascal"
                                asp-action="Index">T-Pascal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitas" asp-action="Index">Libro
                                de Visitas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agenda"
                                asp-action="Agenda">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coockies"
                                asp-action="RegistroCoockies">Coockie</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session"
                                asp-action="RegistroS">Sesiones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SessionesyCookies"
                                asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Captcha"
                                asp-action="VerCaptcha">Capcha</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EJERCICIOS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/calendario.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>